### ISSUE TITLE
Server cannot be opened

### ISSUE THREAD

**Issue by pixelpicosean** [alexlafroscia/atom-ember-cli-helper#2]
When I click the Server button, console logged "Uncaught Error: spawn ENOENT", but the panel shows "Ember CLI Server Started".
Running Atom on: OSX 10.9.3, Node(v0.10.29) installed with nvm.

**Comment by alexlafroscia** [comment]
Hey, did you happen to have this problem when starting the server from `File > Open`? If so, can you please check that things with now with the latest version of the plugin?  I made some changes so that you can configure the paths to `node` and `ember` in the preferences, which are necessary because Atom doesn't seem to add your PATH by default consistently.
