### ISSUE TITLE
More generator options - alterntive script/templating languages

### ISSUE THREAD

**Issue by kristianmandrup** [alexlafroscia/atom-ember-cli-helper#4]
Just wondering... I assume for a project that uses ember-cli-livescript, it imports the livescript blueprints and so it would generate the script files in livescript? or do we need a special option like the coffeescript one? How about emblem templates? EmberScript should also finally work with ember-cli now...

**Comment by alexlafroscia** [comment]
Hey, so I'm actually going to start working on this project again, and next on my list is dynamically generating the possible files to generate.  This might fix your issue here... Maybe?  It will then pull in whatever blueprints are going to be automatically used by `ember generate ....`.  Do you have to pass any kind of additional settings to the generator when you want to use EmberScript or Emblem? I'm unfamiliar with either.

**Comment by ulisesrmzroche** [comment]
ember-cli should automatically detect and generate that for you, I believe. :+1:

**Comment by alexlafroscia** [comment]
Awesome. I'm in the midst of midterms right now, but I actually have the list getting dynamically generated in Atom now.  There's a problem from there, but if I happen to get a spare few hours I'll get this finished up.

**Comment by ulisesrmzroche** [comment]
Ah, cool. Well, let me know if you need any help. I'm pretty interested in this feature right now.

**Comment by ulisesrmzroche** [comment]
Good luck with midterms! :four_leaf_clover:

**Comment by alexlafroscia** [comment]
Thanks :smile: 

If you want to send a PR, I'd be happy to accept it! Otherwise, I'll see if I can tackle it tonight since you're looking for it.

**Comment by ulisesrmzroche** [comment]
No rush though, I understand you're busy right now. I can help you out with
any ember-cli specific stuff but I have some time on the weekend for a PR.
ᐧ
