### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by jpietrangelo** [alexlafroscia/atom-ember-cli-helper#6]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:53:11)
EmberCliHelperView.initialize (/Users/jmp/.atom/packages/ember-cli-helper/lib/ember-cli-helper-view.coffee:22:9)
```

**Comment by alexlafroscia** [comment]
Hey, thanks for pointing this out.  I know that Atom's APIs have changed a lot since I started this, and I know I need to make some updates.  Once I finish dynamically generating the list of generators (which is almost done!) I'm going to get this up to date with the API changes.  Maybe this weekend, if I have some time.

Alternatively, if you want to send me a PR I'd be happy to have the help!  I don't use Atom much anymore so this plugin is pretty low-priority for me, although I want to keep it going so that other Ember lovers have it as a tool.
